### ISSUE TITLE
Tests get stuck when using more threads

### ISSUE THREAD

**Issue by dvdsk** [aschey/stream-download-rs#25] opened 2023-09-26 12:19 UTC
I was trying to speed up the test runs by using `cargo test -- --test-threads=200`. This makes the tests run under 5 seconds except for:

```
seek_all::prefetch_bytes_1_0::seek_from1_2___current__::seek_from2_1___start__::seek_from_val1_2_1::seek_from_val2_1_0::storage_1_TempStorageProvider__default__ has been running for over 60 seconds
```

where it gets stuck. I had a quick look and couldnt really figure this one out :(

**Comment by aschey** [comment] 2023-10-01 01:22
I tried to look into this, but unfortunately I can only reproduce with `cargo test` and not `cargo nextest`. For reasons I haven't bothered to investigate yet, output capturing with the tests only works properly with `nextest`, so unless I can reproduce it there, I can't get a proper output log to follow. I hate to ignore this, but since it seems to work fine with `nextest`, that seems to be the best solution until I can get an output log to follow.

**Comment by aschey** [comment] 2024-03-31 00:18
I'm not sure if something changed or it's just luck, but I haven't been able to reproduce this in a while so I'll close it for now. Some tests fail sporadically under a very large number of threads, but that's expected as the failure is caused by the consumer not being able to keep up with the producer. That would only be fixed by adding backpressure support.

**Closed by aschey** 2024-03-31 00:18 UTC
